FROM registry.access.redhat.com/ubi8/dotnet-60:6.0

USER 0
#RUN dnf update && \
#    dnf upgrade -y && \
RUN  dnf install -y git && \
    dnf clean all -y && \
# ym cache files may still exist (and quite large in size)
    rm -rf /var/cache/yum/*

USER 1001

CMD /usr/libexec/s2i/usage
