FROM registry.access.redhat.com/ubi8/dotnet-80:8.0

USER 0
#RUN dnf update && \
#    dnf upgrade -y && \
RUN  microdnf install -y git && \
    microdnf clean all -y && \
# yum cache files may still exist (and quite large in size)
    rm -rf /var/cache/yum/*

#USER 1001
USER $APP_UID

#CMD /usr/libexec/s2i/usage
CMD /bin/bash
